### ISSUE TITLE
Switch only on/off first time by changing switchOn props.

### ISSUE THREAD

**Issue by benevbright** [dooboolab/react-native-switch-toggle#1]
It works great in most cases. 

Except, turning on/off Switch by changing props, does work only first time.
I will make a PR when I have a chance to code.

**Comment by dooboolab** [comment]
@benevbright please check if you are in version 1.0.4~

**Comment by benevbright** [comment]
@dooboolab 
I'm afraid that I have been using 1.0.4 already.

I looked the code and the module makes display change by `props.switchOn` changing only in `constructor`. If I make change `props.switchOn` later, it won't do anything.
